### PR TITLE
Migrate to Bevy 0.12

### PR DESCRIPTION
**Pull request by tDegan**
Migrate to Bevy 0.12

All examples are migrated as well.

There are a handful of TODOs left, but nothing major.

### CODE REVIEW

**Comment by ecrax** [comment]
having a closer look at this in the coming days, but it looks good as far as I can tell right now :)

**Comment by ghost** [comment]
@ecrax checking in to see if this is the preferred repo for further development?

The other repo looks like it hasn't seen activity in years

**Comment by ecrax** [comment]
Hmm, you're right, the other repo does seem quite abandoned. I'm not sure whether it makes sense to continue development on this repo, though. I don't have the resources to properly maintain this, and the other repo is on crates.io anyway.

I will review and merge the PRs on this repo and maybe even update to Bevy 0.13, but again I wouldn't expect any active maintaining.

**Comment by ghost** [comment]
sounds good, i wouldn't mind working on maintenance. i can also try to reach out to the original developer to see if they are willing to allow access to the original repository to continue the work from there.

**Pull request merged**
